Controllers/DisplayControlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlsAndScaffoldingTemplates.Controllers
{
    public class DisplayControlsController : Controller
    {
        // GET: DisplayControls
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult StepProgressBar()
        {
            return View();
        }
        public ActionResult CheckBoxes()
        {
            return View();
        }
        public ActionResult SliderBar()
        {
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("header", false)

</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        @*<a class="navbar-brand" href="#">Controls Examples</a>*@
        @Html.ActionLink("Controls Examples", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                    @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Students", "Index", "Students", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Enrollments", "Index", "Enrollments", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Courses", "Index", "Courses", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Control Examples
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Checkboxes", "Checkboxes", "DisplayControls", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("StepProgressbar", "StepProgressbar", "DisplayControls", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("SliderBar", "SliderBar", "DisplayControls", null, new { @class = "dropdown-item" })
                        <a class="dropdown-item" href="#">Modal Window Edit</a>
                        <a class="dropdown-item" href="#">Save with Modal Window</a>
                        <a class="dropdown-item" href="#">Toggle Switch</a>
                        <a class="dropdown-item" href="#">Notifications Popdown Window</a>
                        <a class="dropdown-item" href="#">Grid Datatables</a>
                        <a class="dropdown-item" href="#">TextBoxes</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                @*<li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>*@
            </ul>
            <form class="form-inline my-2 my-lg-0" style="padding-right:25px;">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            @Html.Partial("_LoginPartial")
        </div>

    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
    <script type='text/javascript' src='~/Controls/SpellCheckOnAll/include.js'></script>
    <script type='text/javascript'>
        $(document).ready(function () {
            $Spelling.SpellCheckAsYouType('all')
        });
    </script>
</body>
</html>